title: Kelsey Sweeney
description: Electrical Engineering Master's Student portfolio
theme: minima
header_pages:
  - index.md
  - projects/index.md
  - coursework/index.md
  - resume.md
  - contact.md